### ISSUE TITLE
Missing MakeFiles in latest version?

### ISSUE THREAD

**Issue by pcristof** [soylentdeen/MoogStokes#2]
I am trying to install MoogStokes, and I would appear that the readme is not up-to-date. I see a configure file that is apparently a helper to install the code, but at some point I get an cannot find input file: `Makefile.in' error. I also cannot find MakeFiles in the src folder, which may be related?

**Comment by soylentdeen** [comment]
Hi thegreatpolo,  I would recommend using the [MoogPy](https://github.com/soylentdeen/MoogPy) package.  It is a more up to date version of MoogStokes more fully wrapped in Python.
